on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build
        run: go build -o emoGpacked ./cmd/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_emoGpacked
          path: 'emoGpacked'
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0

      - name: Build
        run: go build -o emoGpacked.exe ./cmd/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_emoGpacked
          path: 'emoGpacked.exe'