on:
  workflow_dispatch:
  pull_request:
    branches:
      - c#
  push:
    branches:
      - c#

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - run: dotnet publish -c Release -o .
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_emoGpacked
          path: 'emoGspaced'

  windows_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - run: dotnet publish -c Release -o .
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows_emoGpacked
          path: 'emoGspaced.exe'